// error handling has working with try,catch , finally and throw

// try {
//    run this code
// } catch (err) {
//    if an error happened, then jump here
//    err is the error object
// } finally {
//    do in any case after try/catch
// }





// try means if            //catch means else

// let numbers = 5
// try {
//     if (numbers === 4) {
//     }
//     console.log("It is number 5");
// } catch (error){
//     console.log(error);
// } finally {
//     console.log("Good Question.....")
// }


// finally concept

// try {
//   console.log("try block: The code is running...");
// } catch (error) {
//   console.log(error);
// } finally {
//   console.log("finally block: Executed in all cases.");
// }


// throw concept

// function validateEmail(email) {
//   if (!email.includes("@")) {
//     throw new Error("Invalid email address: '@' character not found!");
//   }
//   return "Valid email address!";
// }

// try {
//   console.log(validateEmail("johnexample.com"));
// } catch (error) {
//   console.log(error);
// }





// // exception handling

// try {
//   number = -9;
//   if (number < 0) {
//     throw "negative number";
//   }
//   console.log(number);
// } catch (error) {
//   console.log(error);
// } finally {
//   console.log("done..");
// }

